### ISSUE TITLE
Video Downloads not working on iOS 12.4

### ISSUE THREAD

**Issue by NickKrahn** [opa334/SafariPlus#16]
When video download in tapped in safari media player, the loading animation around the download icon stays there and doesn’t download the video. (iPhone 7 Plus on iOS 12.4)

**Comment by opa334** [comment]
Video downloads are currently heavily being worked on for 1.7.2. What site are you trying to download from?

**Comment by NickKrahn** [comment]
I’ve tried downloading videos from 9anime.to and YouTube.com so far.

**Comment by opa334** [comment]
@NickKrahn please try this version and check whether this is still an issue: https://www.mediafire.com/file/cf1f9iv9h3kgubu/com.opa334.safariplus_1.7.1-173+debug_iphoneos-arm.deb/file

**Comment by opa334** [comment]
Guess it's fixed
