### ISSUE TITLE
[crash] hold to open crash.

### ISSUE THREAD

**Issue by syto203** [opa334/SafariPlus#17]
On cotomovies.com , tab and hold on the Cydia impactor link will crash safari.
Crash Log.

Date: 2019-08-26 00:48:32 +0000
Process: MobileSafari
Bundle id: com.apple.mobilesafari
Exception type: NSRangeException
Reason: *** -[__NSArrayM insertObject:atIndex:]: index 2 beyond bounds [0 .. 0]
Culprit: SafariPlus.dylib
Device: iPhone X, iOS 12.4
Call stack:
0   CoreFoundation                      0x000000019d7a69a4 __exceptionPreprocess
1   libobjc.A.dylib                     0x000000019c97f9f8 objc_exception_throw
2   CoreFoundation                      0x000000019d7203f8 _CFArgv
3   CoreFoundation                      0x000000019d6910ec -[__NSArrayM removeObjectsInRange:]
4   SafariPlus.dylib                    0x00000001041e41d0 initTabDocument()
5   SafariPlus.dylib                    0x00000001041e0f0c initTabDocument()
6   MobileSafari                        0x00000001006a7fdc MobileSafari + 1064924
7   MobileSafari                        0x00000001006a9c44 MobileSafari + 1072196
8   WebKit                              0x00000001ace25c2c WebKit::UIDelegate::UIClient::actionsForElement(_WKActivatedElementInfo*, WTF::RetainPtr<NSArray>)
9   WebKit                              0x00000001ad0bc3f0 -[WKContentView(WKInteraction) actionSheetAssistant:decideActionsForElement:defaultActions:]
10  WebKit                              0x00000001aceb7bf4 -[WKActionSheetAssistant showLinkSheet]
11  WebKit                              0x00000001accb2890 -[WKContentView(WKInteraction) _longPressRecognized:]
12  UIKitCore                           0x00000001c9d18ac4 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
13  UIKitCore                           0x00000001c9d20ccc _UIGestureRecognizerSendTargetActions
14  UIKitCore                           0x00000001c9d1e670 _UIGestureRecognizerSendActions
15  UIKitCore                           0x00000001c9d1db9c -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:]
16  UIKitCore                           0x00000001c9d11c78 _UIGestureEnvironmentUpdate
17  CoreFoundation                      0x000000019d737d08 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
18  CoreFoundation                      0x000000019d732a30 __CFRunLoopDoObservers
19  CoreFoundation                      0x000000019d732fac __CFRunLoopRun
20  CoreFoundation                      0x000000019d7327c0 CFRunLoopRunSpecific
21  GraphicsServices                    0x000000019f93379c GSEventRunModal
22  UIKitCore                           0x00000001ca0efc38 UIApplicationMain
23  MobileSafari                        0x00000001005a893c MobileSafari + 18748
24  libdyld.dylib                       0x000000019d1f68e0 start

**Comment by opa334** [comment]
Yes, you're right. Will look into this soon!

**Comment by opa334** [comment]
Fixed in 1.7.2!
