### ISSUE TITLE
[Request] Keyboard shortcuts

### ISSUE THREAD

**Issue by Vitalthorbi** [opa334/SafariPlus#18]
SafariPlus is one of the best iPad tweaks I've found! Very cool to have all the additional functionalities.

What would be amazing is support of keyboard shortcuts. 

That means all the desktop/Mac Safari shortcuts and even gestures are available.

Here are a list of all shortcuts/gestures: 
[Shortcuts](https://support.apple.com/guide/safari/keyboard-and-other-shortcuts-cpsh003/mac)

Do you think you can make this happen?

**Comment by opa334** [comment]
Interesting idea, but unlikely to get implemented into Safari Plus, sorry. I don't have any use for this personally and don't even own an iPad. Should definitely be possible tho.
