### ISSUE TITLE
Crashing when holding back to show link history

### ISSUE THREAD

**Issue by ImmortalZypther** [opa334/SafariPlus#19]
When I try to hold the back button to see the full history of links in the session, it'll crash the browser instead.
This issue doesn't exist if I disable the Download Manager (Disabling any other setting does not fix this) in the settings.

Do you know what could be causing this?

### Edit 1:
I did some testing by disabling tweaks using iCleaner, the issue continues even if Safari Plus is the only tweak enabled.
I am on `11.2`, my phone is the `iPhone 6S`, I am using `Electra`; if you need more information, I can provide it.

**Comment by opa334** [comment]
I have a strong feeling I know whats up here. While trying to improve the toolbar reordering options I stumbled across a similar problem so I reverted all the changes for now. It is very possible that this was an issue all along and I just didn't notice it.

When you first start Safari, does the feature work? I believe it should start to crash after rotating to landscape and back a few times.

**Comment by ImmortalZypther** [comment]
My phone has the rotation lock enabled, so it isn't rotating at all during these tests. I also close the app between each test if it still appears in the app switcher.

1. Long press right after opening Safari and going through 2 links so there's a history: Crash
2. Long press after a respring, opening Safari, and going through the same 2 links: Crash
3. Repeat of test 1, but going through 3 links instead of 2 so there's more history: Crash
4. Repeat of test 1, but going back to the first link so there's a forwards history instead and holding the forward history button: Crash
5. Repeat of test 1, but disabling the rotation lock and rotating to landscape mode before holding the back history button: Crash

Note: At seemingly random, when reopening the crashed Safari, the back button input seems to have gone through.
To elaborate: if I was on link 2 from link 1, it would sometimes open to link 1 as if I had just tapped the back history button.
On other times it will stay on link 2; I do not know if this information will help you or not.

If you want me to do any more tests, please tell me.

**Comment by opa334** [comment]
No more test needed, already reproduced this on a 11.1 simulator. It wasn't the issue I thought but something else. Anyways while trying to fix it, I might have found another way of implementing the long press actions that should fix both this and the other issue I was experiencing. This will be resolved soon, likely in 1.7.4.

**Comment by ImmortalZypther** [comment]
Thanks for your quick response!

I'll close this issue when the update comes out; have a nice day~

**Comment by opa334** [comment]
Please try this deb now: https://www.mediafire.com/file/u4zrkyp3bromltu/com.opa334.safariplus_1.7.3-15+debug_iphoneos-arm.deb/file

Check if your issue is fixed and please also verify that I did not break anything else related to the toolbar.

**Comment by ImmortalZypther** [comment]
Installed and tested all the buttons on the toolbar, it seems to work fine. 
Turned off Rotation Lock and tested all the buttons as well, no issues were found.

Closing the issue because now there's a download with no additional issues for anybody who has the same problem.
