### ISSUE TITLE
Custom Search Engine not working on iOS 12.4, iPhone 6

### ISSUE THREAD

**Issue by mmoroni** [opa334/SafariPlus#24]
Even tough I was able to save a new search engine in the tweak settings, it doesn't show in the Safari search engine list.

I force closed the Settings app and force closed Safari to see if it fixes the problem but it doesn't.

**Comment by opa334** [comment]
It's not supposed to show up in the Safari Search Engine list, it will rather overwrite that setting and use the custom one as default.

**Comment by mmoroni** [comment]
Oh, I thought it was by the looks of the source code.

Anyway, it’s also not using the custom search engine by default.

It might be something on my phone, because I didn’t see anybody else with this same problem. :(
