### ISSUE TITLE
Download Manager actually doesn't load anything iOS 12.4 A12

### ISSUE THREAD

**Issue by h0tw4t3r** [opa334/SafariPlus#27]
When I download any file download manager says that the speed is 0KB/s and nothing is going on.
I am 100% sure I have the internet set up.

**Comment by Kai0KenX20** [comment]
![42A3B297-19BD-4D48-A522-4DFF4AFA9B72](https://user-images.githubusercontent.com/49903983/67002918-dc248c00-f0aa-11e9-8b85-fa947cf1dd44.png)
My stuff downloads just fine on iPhone XR 12.4 A12 check your tweaks you might have one that’s conflicting with safari plus

**Comment by h0tw4t3r** [comment]
I don't have much tweaks installed,

- Apps Manager,
- Barmoji,
- BatteryPercent12,
- BetterCCXI,
- Darwin CC Tools,
- Filza,
- iOS Toolchain,
- KillBackgroundXS,
- NewTerm2,
- Noctis12,
- QuickCC,
- ReProvision,
- SmallSiri,
- Snowboard,
- Ultrasound

This is how it looks like:
![IMG_2288](https://user-images.githubusercontent.com/35642018/67004489-b4e8b180-f0e0-11e9-8ec5-eed528194506.PNG)
![IMG_2289](https://user-images.githubusercontent.com/35642018/67004511-c29e3700-f0e0-11e9-8f65-273c675d9649.PNG)

If it is possible I can drop logs, just tell me where are they stored.

**Comment by opa334** [comment]
Run "killall nsurlsessiond" via MTerminal/NewTerm and they will start to work again. There is likely a bug in unc0ver that breaks nsurlsessiond sometimes, causing this issue. Hopefully it will be fixed in the future.

**Comment by Kai0KenX20** [comment]
Was gonna say uninstall letmeblock if you
Have it lol I started having a similar issue getting rid of letmeblock instantly fixed it

**Comment by h0tw4t3r** [comment]
Thank you! Running `killall nsurlsessiond` fixed the issue. 
Would you like to start an issue in https://github.com/pwn20wndstuff/Undecimus or should I do it?
