### ISSUE TITLE
Anyone know the true Safari Tab Limit? I’m at 1650 Tabs and all is well

### ISSUE THREAD

**Issue by badger200** [opa334/SafariPlus#32]
Just wondering how far I can push it. I have a real mental problem with completing old tasks vs opening new ones. 

I back up my Safari app folder BrowserState.db and shm/wal every few weeks. Currently 38MB.

iPad Pro 9.7” (2GB RAM)
iOS 12.4 unc0ver

**Comment by opa334** [comment]
There is no true tab limit as far as I know. I did however experience some weird crashing issues on 13.2 with over 500 tabs, those seem to have been fixed in 13.3 however.

**Comment by badger200** [comment]
Update: now 7500 Tabs on iPad Pro 9.7”
1200 on iPhone 6S.
No issues! Although obviously Safari takes a while to launch, probably 30+ seconds, but less than 60.

I also am suspicious whether this causes issues with iCloud features like Tab / bookmark syncing across devices.

I wouldn’t recommend it but for those of us with various mental illnesses that end up hoarding an insane number of tabs, this tweak is a godsend!! I’m so impressed my iPad, Safari, and Safari Plus can handle such an obscene number of Tabs! Well done! @opa334  👏🏼👏🏼👏🏼👏🏼
