### ISSUE TITLE
YouTube seems to support native player

### ISSUE THREAD

**Issue by pravdomil** [opa334/SafariPlus#35]
I have tweaked your tweak via hex edit to force mobile youtube use the native player and it works as expected and even PiP works too. So do you consider to have setting that forces native player for all sites?

https://github.com/opa334/SafariPlus/blob/c7f806897a347d5d92a795c5c8e62c3b9a1b5be8/MobileSafari/Hooks/SafariWebView.xm#L38

I'm 13.4.

**Comment by opa334** [comment]
You're using an iPad, right? From all the testing I did back when I implemented this feature, YouTube would always use their own player.

**Comment by pravdomil** [comment]
I'm on iPhone.

**Comment by opa334** [comment]
The HTML5 player is only used on iPads to my knowledge. Can you show some screenshots?

**Comment by pravdomil** [comment]
![FBE4A1AD-C9F0-4947-AD9A-3E5539B017C4](https://user-images.githubusercontent.com/2387356/74885631-583f2100-5376-11ea-90e9-ffb192164754.png)

**Comment by opa334** [comment]
Never seen this before lol, do you have a tweak installed that spoofs the device as an iPad maybe? Can you check if it also uses that player when in non-jailbroken mode?

**Comment by pravdomil** [comment]
ok, now i was able to reproduce it
1) enable force native player
1) restart safari and open youtube
1) now the html5 player appears (if not do refresh)
1) disable force native player
1) restart safari and open youtube
1) now the native player appears

no custom agent

**Comment by opa334** [comment]
Fixed in 1.7.11, "Force Native Player" is now hidden on non-iPads.

**Comment by pravdomil** [comment]
well, the thing is very useful, only thing that need to be tweaked is to force native player for all sites, don't know have ipad so don't know what situation is there
