### ISSUE TITLE
Bottom toolbar icons misplaced

### ISSUE THREAD

**Issue by pravdomil** [opa334/SafariPlus#36]
![78660A48-C2F2-44AB-975E-4EFC34DB8B6D](https://user-images.githubusercontent.com/2387356/74885963-309c8880-5377-11ea-8659-503db6c590b3.jpeg)

![67667156-94AC-4484-88E6-68F4A3400097](https://user-images.githubusercontent.com/2387356/74885980-385c2d00-5377-11ea-9eec-fa2a06508581.png)

**Comment by opa334** [comment]
This is an issue with iOS 13 and I can't do anything about it. If you disable "Preview Download Progress" inside Download settings, it will get better.

**Comment by pravdomil** [comment]
aaa, thats a lot better, thank you
