### ISSUE TITLE
Can’t download video

### ISSUE THREAD

**Issue by rabea98** [opa334/SafariPlus#39]
Hi,
I can’t seem to download this video:
https://camcaps.to/video/71/firtsbornunicorn-2b-christmas-cumslut-full-pov

It uses non-standard URL without .mp4 suffix:
https://cdnpro.net/link/JnyCBYxRpDNjkzx/1080/543eb87c7f1804321a39bc78501b97ea/
Also it requires referer and cookies:
Referer: https://cdnpro.net/video/JnyCBYxRpDNjkzx/
Cookie: PHPSESSID=1pj5fdl7m5pmpvu4tg2n128cc5

**Comment by rabea98** [comment]
It uses non-standard URL without .mp4 suffix:
https://cdnpro.net/link/JnyCBYxRpDNjkzx/1080/543eb87c7f1804321a39bc78501b97ea/
Also it requires referer and cookies:
Referer: https://cdnpro.net/video/JnyCBYxRpDNjkzx/
Cookie: PHPSESSID=1pj5fdl7m5pmpvu4tg2n128cc5

**Comment by opa334** [comment]
Sound a lot like #31

**Comment by opa334** [comment]
can't reproduce, the video downloads fine for me
