### ISSUE TITLE
Custom Search Engine not replacing default search engine, iOS 13.3.1

### ISSUE THREAD

**Issue by slio** [opa334/SafariPlus#44]
iOS version - 13.3.1
Device - SE (original)
SafariPlus version - 1.7.12 (cepheiless) , tried with regular version as well.

I had noticed this recently, the settings for Custom Search engine is not working at all. I have been using regular SafariPlus till now and just noticed this today.
I believe the reression came in after last update however I did not catch this till today.

Troubleshooting steps already tried:

- Re-installing normal version
- Re-installing Cepheiless
- Rebooting iOS and rejailbreaking
- Downgrading after installation to 1.7.6 the last version on Cydia.

If you need any logs or specific details please do let me know would try and troubleshoot this.

Additional details : I have seen Preferences crash when navigating to Settings -> Safari -> "Settings for Website" -> Select any value/ Toggle On or OFf (Page Zoom, Request Desktop website, Reader, Content Blockers etc. ) -> Press back
Sometimes it generates a crashlog, sometimes it doesn't. Next time it does will share the same here.

Tweaks installed:
Little 11
Mobilegoose
SafariPlus

**Comment by opa334** [comment]
somehow missed this issue, if this is still an issue then please make sure you put in {searchTerms} as the placeholder and not %s, that's a common user error that prevents it from working
