### ISSUE TITLE
Customizable delay before auto-closing tabs or auto-clearing data

### ISSUE THREAD

**Issue by huynhxloi** [opa334/SafariPlus#47]
Please add a customizable timing delay within the Actions tab before auto-closing or data clearing operations. For example, have a textbox where users can dictate X number of seconds or minutes before the tabs will auto-close or the browser data is cleared. Currently if those Auto actions are chosen, the operation is performed immediately upon Safari minimizing, but if that was accidental then data is needlessly lost.

**Comment by opa334** [comment]
not possible, because once the app is minimized it is impossible for code to run inside it. also too obscure to implement tbh, just set it to clear when the app is closed if you want to avoid unnecessary data loss
