### ISSUE TITLE
Safari Plus not working anymore

### ISSUE THREAD

**Issue by cyus6366** [opa334/SafariPlus#51]
Hello :)

After update from unc0ver 3.31 on IOS13.3 to unc0ver 5.01 on 13.5, I lost the icons download, trash, number of tabs etc.... and all facilities.
uninstalled/ re installed the tweak without success.
Tried to modify settings: nothing.

Any help?

**Comment by opa334** [comment]
Hmm this sounds like outdated dependencies, make sure https://repo.chariz.io/ and https://repo.packix.com/ are added inside your package manager and also make sure that all packages are up to date, other than that, I don't know what to tell you.

**Comment by cyus6366** [comment]
All repo ok and packages updated
It's the only tweak not working properly since the update
Maybe a conflict with another tweak or with substrate ?

**Comment by cyus6366** [comment]
hmmm! Sorry substitute!!!
Uninstalling tweak after tweak but no result...
Gonna check all dependencies in the tweak to be sure that's all ok
Am I the only one on 13.5 to report this malfunction?

**Comment by opa334** [comment]
yes, you're the only one to report this, try a rootFS restore maybe, closing as this isn't a wide spread issue

**Comment by cyus6366** [comment]
Fixed the problem by downgrading cephei to 1.15
Maybe usefull for other  people
