### ISSUE TITLE
Safari plus crashes when using uncover 5.0.1 and above

### ISSUE THREAD

**Issue by jack2247** [opa334/SafariPlus#56]
I have tried jailbreaking through every version of uncover from 5.0.0 to 5.2.1 and safari plus only works on 5.0.0.
I am using iphone 6s on ios 13.5
When I try to open safari with safari plus enabled it crashes and again when I try to open safari it work but without safari plus, it open as a simple default browser without any tweaks.
I love this tweak so please help me to solve this issue.
I have also tried after disabling all the features but still it crashes.
Thank you

**Comment by Kai0KenX20** [comment]
Can you provide any information im using safari plus just fine unc0ver 5.2.1 and have been every version below

**Comment by jack2247** [comment]
> Can you provide any information im using safari plus just fine unc0ver 5.2.1 and have been every version below

Sorry, mistakenly I pressed enter when I was writing the title and because of that the issue got submitted without description. Now I have added description.

**Comment by Kai0KenX20** [comment]
Do you have cr4shed installed a crashlog might help out opa334 more you can use https://pastebin.com/ to upload a crash log if you have/aquire one..... may i ask why you don’t update to unc0ver 5.2.1 I’ve been outta the loop a bit but i believe it supports that iOS/iDevice.... are their and benefits to the version of unc0ver your running?...... more dumb notes lol srry but make sure your getting safari plus from oppa334’s actual repo https://opa334.github.io/

**Comment by jack2247** [comment]
Cr4shed is install on my phone but this crash is not logged in it and I have installed the tweak from official Repo only. Right now I am using unc0ver 5.2.1.
Reseting my phone is the last option.
Okay I will check in cydia if there are any essential updates.

**Comment by jack2247** [comment]
Its working, when I tried after doing rootfs it is working so there might me someone conflicts in the tweaks I installed previously, anyways thank you.
