### ISSUE TITLE
Enabling locked tabs in options on iOS 14 cause safari to crash.

### ISSUE THREAD

**Issue by nathanielcwm** [opa334/SafariPlus#61]
When locked tabs are enabled in settings Safari crashes every single time on iOS 14.1

iOS 14.1
iPad Pro 9.7
Odysseyra1n

I'll attach the crash log in a moment.

**Comment by nathanielcwm** [comment]
Actually it looks like enabling any of the options causes a crash e.g:
Enabling open in opposite mode crashes safari when holding a link
Enabling tab numbers also causes a crash on startup
Haven't tested any more yet.

**Comment by opa334** [comment]
Safari Plus does not support iOS 14

**Comment by nathanielcwm** [comment]
Well that explains all the issues ;p

**Comment by opa334** [comment]
Fixed in 1.7.14~b1
