### ISSUE TITLE
Podcasts from RaiPlay Radio can't be downloaded

### ISSUE THREAD

**Issue by Tizioincognit0** [opa334/SafariPlus#62]
When I try to download podcasts from RaiPlay Radio (e.g.: https://www.raiplayradio.it/programmi/610seiunozero/), it doesn't start unless I open Safari with the tweak Safari Plus disabled and I use the iOS Safari built-in downloader.
I'm using an iPhone X on iOS 13.4.1 jailbroken with Unc0ver.

**Comment by opa334** [comment]
Yeah blob links are unsupported and I'm not sure if I can do anything about that

**Comment by opa334** [comment]
"fixed" in 1.7.14, blob links are now automatically redirected to the safari download manager
