### ISSUE TITLE
Option to enable the ability for safari webapps to have background playback and pip

### ISSUE THREAD

**Issue by linusrg1** [opa334/SafariPlus#66]
I realized that when I made a site pip with safari, safari disabled its ability to have pip and background playback, it would be cool if there was an option to add this back into the player

**Comment by badger200** [comment]
I believe it’s Julioverne who has playbackSafari or playbackgroundSafari tweak that does this. I have it installed and it works with PIP. If it’s not JV then it’s CydiaGeek.

Try repo julioverne.github.io

**Comment by linusrg1** [comment]
> I believe it’s Julioverne who has playbackSafari or playbackgroundSafari tweak that does this. I have it installed and it works with PIP. If it’s not JV then it’s CydiaGeek.
> 
> Try repo julioverne.github.io

You know what the issue resolved itself when updating to 14.5 (i use checkra1n which is why i updated.)
