### ISSUE TITLE
Wont load XR iOS 14 

### ISSUE THREAD

**Issue by Kai0KenX20** [opa334/SafariPlus#67]
When trying to load safari it immediately crashes on my XR iOS 14.3.... sorry no logs cr4shed doesn’t seem to be working as well... if someone knows another way I could provide a log to help I will.... I NEED MY SAFARI PLUS! 😬

**Comment by opa334** [comment]
known as the patchfinder had never been tested on arm64e before, will be looked into today

**Comment by Kai0KenX20** [comment]
Awesome! thank you so much

**Comment by Kai0KenX20** [comment]
Wanted to say thank you very much sir for looking into this fixing and closing this issue Safari plus is one of my must haves and I can’t thank you enough may fortune always shine upon you sir
