### ISSUE TITLE
Pending download stuck and slow downloads

### ISSUE THREAD

**Issue by AndrewXin123** [opa334/SafariPlus#7]
I have a few pending downloads which show "Zero KB @ Zero KB/s" and "Unknown Size" and I cannot remove them or resume the download.

My downloads are all very slow, I have a good connection but only manage 300-400 KB/s. The only way I discovered to speed it up was to pause and play the download but it only speeds it up to 2 MB/s for a second.

**Comment by opa334** [comment]
Removing the frozen downloads can be done by using the Clear -> Cancel All Downloads option inside the downloads menu.

Download speeds can depend on the site, especially video streams often have a capped bandwidth. A good benchmark site that doesn't cap you is https://speed.hetzner.de, please try to download a file from there and check if the speed is still slow.

**Comment by AndrewXin123** [comment]
Just found out the bandwidth of the site is capped. Thank you for the quick reply!
