### ISSUE TITLE
Random crash when open Safari

### ISSUE THREAD

**Issue by Halo-Michael** [opa334/SafariPlus#71]
After upgrade substitute to 2.0.10, Safari gots random crash when open it. Crash log showes Abort function was called.
![41934438-B72A-4CAE-8469-AFE44692AF61](https://user-images.githubusercontent.com/45062120/112481707-41a59d80-8db2-11eb-89b7-9fce52a45189.png)

**Comment by opa334** [comment]
please post the full crash log

**Comment by Halo-Michael** [comment]
`![MobileSafari-2021-03-25-213429.symbolicated.ips](https://github.com/Halo-Michael/tmp/raw/master/MobileSafari-2021-03-25-213429.symbolicated.ips)`

**Comment by Halo-Michael** [comment]
One of the crash logs

**Comment by opa334** [comment]
interesting, doubt it has something to do with the substitute update, can you also provide a log from cr4shed?

**Comment by opa334** [comment]
https://github.com/opa334/SafariPlus/blob/master/MobileSafari/Classes/SPFileManager.mm#L99 this is the line of code that causes the crash, as far as I'm aware it can only crash if NSTemporaryDirectory returns something unexpected

**Comment by Halo-Michael** [comment]
Open a sharing link will 100% cause the crash:
![IMG_2372.MP4](https://github.com/Halo-Michael/tmp/raw/master/IMG_2372.MP4)
And here is the log from cr4shed:
![MobileSafari%402021-03-26_12:25_.log](https://github.com/Halo-Michael/tmp/raw/master/MobileSafari%402021-03-26_12:25_.log)

**Comment by opa334** [comment]
can't reproduce it unfortunately

**Comment by opa334** [comment]
can you check if downgrading Substitute to 2.0.9 fixes the issue?

**Comment by Halo-Michael** [comment]
> can you check if downgrading Substitute to 2.0.9 fixes the issue?

Well yes...

**Comment by opa334** [comment]
Well as you saw on Twitter I found an issue that could be related to this crash but I was able to reproduce that on Substitute 2.0.9 too so I doubt the 2.0.10 has anything to do with it. I'm still investigating however.

**Comment by opa334** [comment]
can you check if this version fixes it? https://www.mediafire.com/file/5t74hnohf3gt1un/com.opa334.safariplus_1.7.15-17%252Bdebug_iphoneos-arm.deb/file

**Comment by Halo-Michael** [comment]
> can you check if this version fixes it? https://www.mediafire.com/file/5t74hnohf3gt1un/com.opa334.safariplus_1.7.15-17%252Bdebug_iphoneos-arm.deb/file

Seems yes when I open a sharing link from other apps, but maybe I should observe for more time.

**Comment by Halo-Michael** [comment]
> > can you check if this version fixes it? https://www.mediafire.com/file/5t74hnohf3gt1un/com.opa334.safariplus_1.7.15-17%252Bdebug_iphoneos-arm.deb/file
> 
> Seems yes when I open a sharing link from other apps, but maybe I should observe for more time.

No other crashes found, should be fixed now.
