### ISSUE TITLE
Getting around Ver. Requirements 

### ISSUE THREAD

**Issue by ralphieb2t** [opa334/SafariPlus#80]
I’m beginning to have the issue come up of websites that want to require newer versions of Safari on an IOS 13jb A10 device. If there’s a way to get around this as of now on S+, I’m not seeing it.

**Comment by ralphieb2t** [comment]
![Uploading 74ECB28E-540A-44C0-9D86-753CB41433EE.png…]()

**Comment by ralphieb2t** [comment]
![65FEE7F0-6490-44B3-B855-1EA0369C2127](https://user-images.githubusercontent.com/73906926/130552211-c4168bc9-9614-403f-855e-dda61b2b8de8.png)

**Comment by opa334** [comment]
Customization -> Custom User Agent
