### ISSUE TITLE
[bug] downloads don’t register as actually being in Filza

### ISSUE THREAD

**Issue by ralphieb2t** [opa334/SafariPlus#82]
Describe the bug:
(14.5.1 12Pro Max)
Using the download manager, when you download something & press *see in Filza; the downloads do not register as actually being there.

Steps to produce bug: 
1.) download something
2.) click see in Filza
3.) try n’ do something w/ the file ie: copy the file, attempt to click Move file
4.) BOOM! There’s the bug. Most times it would just select the file but not actually do anything. The more I messed around with it though, I did end up getting the msg *file does not exist* or something along those lines. But it was certainly there, I was able to move it from the download manager to a diff app.

**Comment by opa334** [comment]
I don't have a 14.5.1 device so I can't try to reproduce, to me this sounds like a Filza bug however. Safari Plus doesn't interact with Filza in any way, it just opens it at the file path and that's it.

**Comment by ralphieb2t** [comment]
> I don't have a 14.5.1 device so I can't try to reproduce, to me this sounds like a Filza bug however. Safari Plus doesn't interact with Filza in any way, it just opens it at the file path and that's it.

Thanks for responding; to tell you the truth, I   was kinda contemplating that after I posted it. I’m not a Dev or anything tho, so i figured hey, what do I know how this stuff works;) I could take a vid or something at some point if need be. Perhaps, I’ll post the bug on Filza’s page as well so hopefully someone can get to the bottom of it. 

Also, while I’ve got your attention— I’ve had some issues with the “Desktop mode” button, the one you can turn on in the toolbar. This is an issue I’ve had on lower FW’s as well. If you go to a page, click out, then click the icon & go back in— if afterwards, you click the “Aa” in the upper right-hand corner, it should still say “request desktop?”  Indicating that it is still in mobile mode. Appreciate the help. 

P.S. Safari Plus always within my top 3 tweaks to download after JB!! Now that’s a prestigious tweak-status :D

**Comment by opa334** [comment]
The desktop mode works differently, it just spoofes the user agent, I never adjusted it to work with the stock switching feature of iOS 14, maybe I will implement that in a future version.

Closing this for now, feel free to send me a screen recording via twitter dm or similar.
