### ISSUE TITLE
Custom Search Engines

### ISSUE THREAD

**Issue by kainanakidd** [opa334/SafariPlus#9]
Could this please be added? For example, using StartPage or Searx as the search engine rather than the options provided. Thank you.

Url Schemes:
StartPage: https://www.startpage.com/do/dsearch?query=%s
Searx:
https://searx.me/?q=%s

**Comment by AJGists** [comment]
Yesssss... custom search engines would be so nice.

**Comment by Starbix** [comment]
Why is the issue closed? I would love to have this feature.

**Comment by opa334** [comment]
The issue was closed because the feature was implemented in 1.7. It's available under "Customization".
