### ISSUE TITLE
[BUG] No Communication with webprocess

### ISSUE THREAD

**Issue by Th3C0D3R** [opa334/SafariPlus#90]
Since some days I get this message whenever I try to download a video:
![90E0DF3E-44E2-4EFC-8BCB-016B38CA0938](https://user-images.githubusercontent.com/7798500/194114196-5c7468f3-b0e6-43b9-a5a7-0768a1f90c92.jpeg)

English:
"The communication with the
WebContent process is
failed. This is for retrieval
of the video URL is required. Job
sure that SafariPlusWC.dylib not
with iCleaner Pro, Choice or
similar tweaks has been disabled.
Since you are using libhooker, also ask
sure that the option 'Allow tweaks in
webpages' in libhooker Configurator
is activated and that both libhooker
as well as your jailbreak on the latest
version are."

I tried to reinstall the tweak. looked into iCleaner and libhooker, but nothing that I changed made it better, I also updated the jailbreak to the latest version:

iOS 14.3
Taurine 1.1.6 (was not working with the version before)
libhooker 1.6.9 (cannot find a previous version else I would tried it)
Did also not update any tweak that would conflict with it

**Comment by opa334** [comment]
Should work, that's all I can say

**Comment by Th3C0D3R** [comment]
I disabled all tweaks except SafariPlus and the dependencies 
Still same message.

//edit
Older Versions also not work. So it should bot be a problem with the tweak.

**Comment by Th3C0D3R** [comment]
Ok... don't know what happed but now it works... really strange...

**Comment by Th3C0D3R** [comment]
Ok was not true,
I removed the tweak, cleared everything with iCleaner
and installed the Cepheiless version of Safari Plus.

**Comment by opa334** [comment]
Don't install the Cepheiless version, it's no longer supported, the main version no longer depends on Cephei.

**Comment by Th3C0D3R** [comment]
Yeah maybe, but it works for me.
I will try to install the normal version and see if its the problem

**Comment by Th3C0D3R** [comment]
Yeah worked now with the normal version too... I don't understand this.
Sorry for the issue, literally
