### ISSUE TITLE
Unable to get custom search engine working

### ISSUE THREAD

**Issue by JCDC85** [opa334/SafariPlus#94]
I am unable to get the custom search engine function working. I put the switch in the on position, Mojeek for search engine name, https://www.mojeek.com/search?q={searchterms} for Search URL. 
Safari still uses default search selected in safari settings. 
Ive tried respringing and closing/re-opening the Safari app.

**Comment by opa334** [comment]
it's {searchTerms} not {searchterms}

**Comment by JCDC85** [comment]
Had no idea it was case sensitive. Thank you.
