### ISSUE TITLE
movpkgmerge.py Script does not seem to work

### ISSUE THREAD

**Issue by RamanMehat** [opa334/SafariPlus#96]
I have updated movpkgmerge.py to find the correct .mu38 files; however, it does not seem to convert the file correctly. Seems to have no Audio. 

I am trying to convert Podcast movpkg files to audio files (mp4/mp3)

**Comment by opa334** [comment]
Hm idk, haven't used or looked at that in years, if you have a device running Safari Plus you can always press the movpkg file there and select "Merge to .ts file"

**Comment by sussyboiiii** [comment]
> 



> Hm idk, haven't used or looked at that in years, if you have a device running Safari Plus you can always press the movpkg file there and select "Merge to .ts file"

Can't we convert the .movpkg file just using the python document? Would be easier.

**Comment by opa334** [comment]
ah I forgot, the file not having any audio is normal, the layers are split in the movpkg, if you want audio and video synced you need to mux the two layers together using some external software
